# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1267, 742)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-80, -10, 1951, 811))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("bg/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 471, 311))
        self.bg_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(490, 10, 481, 311))
        self.bg_3.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 20, 451, 291))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("bg/ironmanwoo.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(500, 20, 461, 291))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("extraGui/Hero_Template.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(980, 10, 281, 211))
        self.bg_4.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(990, 20, 261, 191))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("extraGui/Earth.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time.setGeometry(QtCore.QRect(1070, 660, 171, 41))
        self.Text_Time.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 0, 255);\n"
"font: 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 170, 255);\n"
"border-radius: none;\n"
"")
        self.Text_Time.setObjectName("Text_Time")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(990, 640, 261, 81))
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("bg/images.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(10, 310, 261, 301))
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(990, 560, 261, 81))
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("bg/images.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(990, 480, 261, 81))
        self.bg_8.setText("")
        self.bg_8.setPixmap(QtGui.QPixmap("bg/images.jpg"))
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.Text_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Day.setGeometry(QtCore.QRect(1070, 580, 171, 41))
        self.Text_Day.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 0, 255);\n"
"font: 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 170, 255);\n"
"border-radius: none;\n"
"")
        self.Text_Day.setObjectName("Text_Day")
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(1070, 500, 171, 41))
        self.Text_Date.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 0, 255);\n"
"font: 10pt \"MS Sans Serif\";\n"
"color: rgb(0, 170, 255);\n"
"border-radius: none;\n"
"")
        self.Text_Date.setObjectName("Text_Date")
        self.bg_9 = QtWidgets.QLabel(self.centralwidget)
        self.bg_9.setGeometry(QtCore.QRect(990, 400, 261, 81))
        self.bg_9.setText("")
        self.bg_9.setPixmap(QtGui.QPixmap("bg/images.jpg"))
        self.bg_9.setScaledContents(True)
        self.bg_9.setObjectName("bg_9")
        self.Text_Temperature = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Temperature.setGeometry(QtCore.QRect(1090, 420, 171, 41))
        self.Text_Temperature.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 0, 255);\n"
"font: 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 170, 255);\n"
"border-radius: none;\n"
"")
        self.Text_Temperature.setObjectName("Text_Temperature")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(990, 240, 261, 31))
        self.pushButton_start.setStyleSheet("font: 8pt \"Terminal\";\n"
"background-color: black;\n"
"border-radius: none;\n"
"color: rgb(170, 170, 255);\n"
"font: 16pt \"MS Sans Serif\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.bg_10 = QtWidgets.QLabel(self.centralwidget)
        self.bg_10.setGeometry(QtCore.QRect(980, 230, 281, 91))
        self.bg_10.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.bg_10.setText("")
        self.bg_10.setObjectName("bg_10")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(990, 280, 261, 31))
        self.pushButton_exit.setStyleSheet("font: 8pt \"Terminal\";\n"
"background-color: black;\n"
"border-radius: none;\n"
"color: rgb(170, 170, 255);\n"
"font: 16pt \"MS Sans Serif\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_youtube.setGeometry(QtCore.QRect(490, 350, 161, 41))
        self.pushButton_youtube.setStyleSheet("font: 18pt \"PMingLiU-ExtB\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_youtube.setObjectName("pushButton_youtube")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(660, 350, 151, 41))
        self.pushButton_chrome.setStyleSheet("font: 18pt \"PMingLiU-ExtB\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(820, 350, 151, 41))
        self.pushButton_whatsapp.setStyleSheet("font: 18pt \"PMingLiU-ExtB\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(20, 440, 461, 321))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("voiceReg/Aqua.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(10, 340, 471, 171))
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap("bg/voicegrf.gif"))
        self.gif_5.setScaledContents(True)
        self.gif_5.setObjectName("gif_5")
        self.bg_5.raise_()
        self.bg_1.raise_()
        self.bg_10.raise_()
        self.bg_6.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.gif_1.raise_()
        self.gif_2.raise_()
        self.bg_4.raise_()
        self.gif_4.raise_()
        self.Text_Time.raise_()
        self.bg_7.raise_()
        self.bg_8.raise_()
        self.Text_Day.raise_()
        self.Text_Date.raise_()
        self.bg_9.raise_()
        self.Text_Temperature.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_youtube.raise_()
        self.pushButton_chrome.raise_()
        self.pushButton_whatsapp.raise_()
        self.gif_3.raise_()
        self.gif_5.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JarvisUi)
        self.statusbar.setObjectName("statusbar")
        JarvisUi.setStatusBar(self.statusbar)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.Text_Time.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.Text_Day.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.Text_Date.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Text_Temperature.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.pushButton_start.setText(_translate("JarvisUi", "START"))
        self.pushButton_exit.setText(_translate("JarvisUi", "EXIT"))
        self.pushButton_youtube.setText(_translate("JarvisUi", "YouTube"))
        self.pushButton_chrome.setText(_translate("JarvisUi", "Chrome"))
        self.pushButton_whatsapp.setText(_translate("JarvisUi", "Whatsapp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
